Resources:
  StatsActionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: actionType
          AttributeType: S
        - AttributeName: createdDate
          AttributeType: S
        - AttributeName: idea_owner_id
          AttributeType: S
      KeySchema:
        - AttributeName: actionType
          KeyType: HASH
        - AttributeName: createdDate
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.statsActionsTableName}
      GlobalSecondaryIndexes:
        - IndexName: ownerStatsByDate
          KeySchema:
            - AttributeName: idea_owner_id
              KeyType: HASH
            - AttributeName: createdDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
