Resources:
  SavesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ideaId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: ideaOwnerId
          AttributeType: S
        - AttributeName: savedTime
          AttributeType: S
      KeySchema:
        - AttributeName: ideaId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.savesTableName}
      GlobalSecondaryIndexes:
        - IndexName: userSaves
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: userSavesByDate
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: savedTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: ownerSavesByDate
          KeySchema:
            - AttributeName: ideaOwnerId
              KeyType: HASH
            - AttributeName: savedTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
