Resources:
  FullDBAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:provider.stage}FullDBAccessRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ${self:provider.stage}CustomCloudWatchLogsPolicy-
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:logs'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'log-group:/aws/lambda/*:*:*'
        - PolicyName: ${self:provider.stage}FullDBAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:*"
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.commentsTableName}'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.commentsTableName}/*'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.ideaCommentsTemporaryTableName}'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.ideaCommentsTemporaryTableName}/*'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.followingTableName}'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.followingTableName}/*'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.ideasTableName}'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.ideasTableName}/*'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.likesTableName}'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.likesTableName}/*'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.migrationsTableName}'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.migrationsTableName}/*'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.savesTableName}'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.savesTableName}/*'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.statsActionsTableName}'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.statsActionsTableName}/*'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.tagsTableName}'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.tagsTableName}/*'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.usersTableName}'
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.usersTableName}/*'
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
